### PR TITLE
Add missing test artifacts on linux

### PR DESCRIPTION
**Pull request by ziyu-guo**
Add missing artifacts and data files for integration tests on linux platforms.

### CODE REVIEW

**Comment by wweic** [comment]
Thanks @ziyu-guo . Could you also add documentation about how to run these tests?

**Comment by zhiics** [comment]
I think adding a few artifacts like this is okay, but we probably need to figure out a better way to add artifacts for integration tests because the the params files are usually quite big. Hence, the size of test folder will blow if we keep adding more and more integration test.

**Comment by wweic** [comment]
Agree @zhiics. Probably we can store the integration test artifacts in s3 and download on demand.

**Comment by wweic** [comment]
created https://github.com/neo-ai/neo-ai-dlr/issues/9 to follow up the integrate test artifacts issue.

**Pull request merged**
