### PR TITLE
Retrieve matching linux TVM test model artifacts from S3 based on Processor Architecture

### LINKED ISSUE #9: Store integration test artifacts in S3 and download on demand
so we won't need to store them in the repo.

### PR DESCRIPTION
**Pull request by ziyu-guo**
And remove model artifacts from this repo

Public S3 folder at s3://neo-ai-dlr-test-artifacts/

Closes #9

### CODE REVIEW

**Comment by hcho3** [comment]
Let me also add Treelite artifacts too

**Comment by hcho3** [comment]
@ziyu-guo For "x86_64" target, which instance did you use to compile? Models compiled for C5 target doesn't run on C4 or M4, for example (due to use of AVX512).

**Comment by ziyu-guo** [comment]
> @ziyu-guo For "x86_64" target, which instance did you use to compile? Models compiled for C5 target doesn't run on C4 or M4, for example (due to use of AVX512).

X64_64 artifacts are compiled with just "-llvm" in centos6 docker for compatibility. These are CPU-only models.

**Comment by hcho3** [comment]
@ziyu-guo So it's safe to assume that it would run for all x86_64 targets (it won't use fancy AVX etc)?

**Comment by ziyu-guo** [comment]
@hcho3 Yes, compatibility instead of opt level in this correctness test.

**Comment by wweic** [comment]
Change LGTM. Could you also add the integration test into Jenkins? @ziyu-guo

**Comment by hcho3** [comment]
@wweic Will add the test into Jenkins today.

**Comment by hcho3** [comment]
Uh oh, the assertion for LETOR is failing. Let me run this on my machine.

**Pull request merged**
